name: test_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.5.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_local_notifications: ^9.6.1
  firebase_messaging: ^11.4.2
  firebase_core: ^1.18.0
  yandex_mapkit: ^3.0.1
  #
  shimmer: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
